name: Periodic health check

on:
  schedule:
    - cron: '15 2 * * *'

jobs:
  schedule_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-vc4o.onrender.com/
      - name: Health Check
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          details: |
            /ping was successful
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
